nodeLinker: node-modules # uses node_modules instead of Yarn's Plug'n'Play
defaultSemverRangePrefix: '' # pins dependencies to exact versions during install
enableScripts: false # prevents 3rd party packages from running postinstall scripts
enableImmutableInstalls: true # Equivalent to --frozen-lockfile
